stages:
  - test-firefox
  - test-chrome

test-chrome:
  stage: test-chrome
  image: node:latest
  services:
    - selenium/standalone-chrome:latest
  variables:
    RACK_ENV: "test"
    SELENIUM_URL: "http://selenium__standalone-chrome:4444/wd/hub"
    GITLAB_CI: "true"
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --prefer-offline
  script:
    - npm run build
    - npm run test

test-firefox:
  stage: test-firefox
  image: node:latest
  services:
    - selenium/standalone-firefox:latest
  variables:
    RACK_ENV: "test"
    SELENIUM_FIREFOX_URL: "http://selenium__standalone-firefox:4444/wd/hub"
    GITLAB_CI: "true"
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --prefer-offline
  script:
    - npm run build
    - npm run test
