'use strict';

/** @namespace MMSystem */

import { Module } from './module.js';

import {
  BYTE,
  UBYTE,
  INT,
  UINT,
  FARPTR,
  DWORD,
  HLOCAL,
  HGLOBAL,
  HANDLE,
  Struct,
  BOOL,
  NEARPTR,
  LPCSTR,
  HWND,
} from './types.js';

import { midiOutGetNumDevs } from './mmsystem/midiOutGetNumDevs.js';
import {
  waveGetDevCaps,
  waveGetErrorText,
  waveInGetNumDevs,
  waveOpen,
  waveOutGetNumDevs,
} from './mmsystem/devices.js';

/**
 * The Win16 Multimedia System library.
 *
 * @memberof Win16
 */
export class MMSystem extends Module {
  declare static CALLBACK_FUNCTION: any;
  declare static CALLBACK_TASK: any;
  declare static CALLBACK_WINDOW: any;
  declare static JOYERR_BASE: any;
  declare static MCIERR_BASE: any;
  declare static MIDIERR_BASE: any;
  declare static MMSYSERR_ALLOCATED: any;
  declare static MMSYSERR_BADDEVICEID: any;
  declare static MMSYSERR_BADERRNUM: any;
  declare static MMSYSERR_BASE: any;
  declare static MMSYSERR_ERROR: any;
  declare static MMSYSERR_INVALFLAG: any;
  declare static MMSYSERR_INVALHANDLE: any;
  declare static MMSYSERR_INVALPARAM: any;
  declare static MMSYSERR_LASTERROR: any;
  declare static MMSYSERR_NODRIVER: any;
  declare static MMSYSERR_NOERROR: any;
  declare static MMSYSERR_NOMEM: any;
  declare static MMSYSERR_NOTENABLED: any;
  declare static MMSYSERR_NOTSUPPORTED: any;
  declare static TIMERR_BASE: any;
  declare static WAVERR_BASE: any;
  declare static WAVE_ALLOWSYNC: any;
  declare static WAVE_FORMAT_PCM: any;
  declare static WAVE_FORMAT_QUERY: any;
  declare static WAVE_MAPPER: any;
  static get name(): string {
    return 'MMSYSTEM';
  }

  static get path() {
    return 'C:\\WINDOWS\\SYSTEM\\MMSYSTEM.DLL';
  }

  static get exports() {
    return [
      // 0 // "System APIs for Multimedia"
      null,
      [MMSystem.stub, 'unknown', 2],
      [MMSystem.stub, 'sndPlaySound', 6],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'mmsystemGetVersion', 0],
      [MMSystem.stub, 'unknown', 16],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 10 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 20 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 30 //
      [MMSystem.stub, 'OutputDebugStr', 4],
      [MMSystem.stub, 'DriverCallback', 22],
      [MMSystem.stub, 'StackEnter', 0],
      [MMSystem.stub, 'StackLeave', 0],
      [MMSystem.stub, 'mmDrvInstall', 8],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 40 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 50 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 60 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 70 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 80 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 90 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 100 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'joyGetNumDevs', 0],
      [MMSystem.stub, 'joyGetDevCaps', 8],
      [MMSystem.stub, 'joyGetPos', 6],
      [MMSystem.stub, 'joyGetThreshold', 6],
      [MMSystem.stub, 'joyReleaseCapture', 2],
      [MMSystem.stub, 'joySetCapture', 8],
      [MMSystem.stub, 'joySetThreshold', 4],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'joySetCalibration', 26],
      // 110 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 120 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 130 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 140 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 150 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 160 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 170 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 180 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 190 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 200 //
      [MMSystem.stub, 'unknown'],
      [midiOutGetNumDevs, 'midiOutGetNumDevs', 0, [], UINT],
      [MMSystem.stub, 'midiOutGetDevCaps', 8],
      [MMSystem.stub, 'midiOutGetErrorText', 8],
      [MMSystem.stub, 'midiOutOpen', 18],
      [MMSystem.stub, 'midiOutClose', 2],
      [MMSystem.stub, 'midiOutPrepareHeader', 8],
      [MMSystem.stub, 'midiOutUnprepareHeader', 8],
      [MMSystem.stub, 'midiOutShortMsg', 6],
      [MMSystem.stub, 'midiOutLongMsg', 8],
      // 210 //
      [MMSystem.stub, 'midiOutReset', 2],
      [MMSystem.stub, 'midiOutGetVolume', 6],
      [MMSystem.stub, 'midiOutSetVolume', 6],
      [MMSystem.stub, 'midiOutCachePatches', 10],
      [MMSystem.stub, 'midiOutCacheDrumPatches', 10],
      [MMSystem.stub, 'midiOutGetID', 6],
      [MMSystem.stub, 'midiOutMessage', 12],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 220 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 230 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 240 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 250 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 260 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 270 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 280 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 290 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 300 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'midiInGetNumDevs', 0],
      [MMSystem.stub, 'midiInGetDevCaps', 8],
      [MMSystem.stub, 'midiInGetErrorText', 8],
      [MMSystem.stub, 'midiInOpen', 18],
      [MMSystem.stub, 'midiInClose', 2],
      [MMSystem.stub, 'midiInPrepareHeader', 8],
      [MMSystem.stub, 'midiInUnprepareHeader', 8],
      [MMSystem.stub, 'midiInAddBuffer', 8],
      [MMSystem.stub, 'midiInStart', 2],
      // 310 //
      [MMSystem.stub, 'midiInStop', 2],
      [MMSystem.stub, 'midiInReset', 2],
      [MMSystem.stub, 'midiInGetID', 6],
      [MMSystem.stub, 'midiInMessage', 12],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 320 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 330 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 340 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 350 //
      [MMSystem.stub, 'auxGetNumDevs', 0],
      [MMSystem.stub, 'auxGetDevCaps', 8],
      [MMSystem.stub, 'auxGetVolume', 6],
      [MMSystem.stub, 'auxSetVolume', 6],
      [MMSystem.stub, 'auxOutMessage', 12],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 360 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 370 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 380 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 390 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 400 //
      [MMSystem.stub, 'unknown'],
      [waveOutGetNumDevs, 'waveOutGetNumDevs', 0, [], UINT],
      [waveGetDevCaps, 'waveOutGetDevCaps', 8, [UINT, FARPTR, UINT], UINT],
      [waveGetErrorText, 'waveOutGetErrorText', 8, [UINT, FARPTR, UINT], UINT],
      [waveOpen, 'waveOutOpen', 22, [FARPTR, UINT, FARPTR, DWORD, DWORD, DWORD], UINT],
      [MMSystem.stub, 'waveOutClose', 2],
      [MMSystem.stub, 'waveOutPrepareHeader', 8],
      [MMSystem.stub, 'waveOutUnprepareHeader', 8],
      [MMSystem.stub, 'waveOutWrite', 8],
      [MMSystem.stub, 'waveOutPause', 2],
      // 410 //
      [MMSystem.stub, 'waveOutRestart', 2],
      [MMSystem.stub, 'waveOutReset', 2],
      [MMSystem.stub, 'waveOutGetPosition', 8],
      [MMSystem.stub, 'waveOutGetPitch', 6],
      [MMSystem.stub, 'waveOutSetPitch', 6],
      [MMSystem.stub, 'waveOutGetVolume', 6],
      [MMSystem.stub, 'waveOutSetVolume', 6],
      [MMSystem.stub, 'waveOutGetPlaybackRate', 6],
      [MMSystem.stub, 'waveOutSetPlaybackRate', 6],
      [MMSystem.stub, 'waveOutBreakLoop', 2],
      // 420 //
      [MMSystem.stub, 'waveOutGetID', 6],
      [MMSystem.stub, 'waveOutMessage', 12],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 430 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 440 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 450 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 460 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 470 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 480 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 490 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 500 //
      [MMSystem.stub, 'unknown'],
      [waveInGetNumDevs, 'waveInGetNumDevs', 0, [], UINT],
      [waveGetDevCaps, 'waveInGetDevCaps', 8, [UINT, FARPTR, UINT], UINT],
      [waveGetErrorText, 'waveInGetErrorText', 8, [UINT, FARPTR, UINT], UINT],
      [waveOpen, 'waveInOpen', 22, [FARPTR, UINT, FARPTR, DWORD, DWORD, DWORD], UINT],
      [MMSystem.stub, 'waveInClose', 2],
      [MMSystem.stub, 'waveInPrepareHeader', 8],
      [MMSystem.stub, 'waveInUnprepareHeader', 8],
      [MMSystem.stub, 'waveInAddBuffer', 8],
      [MMSystem.stub, 'waveInStart', 2],
      // 510 //
      [MMSystem.stub, 'waveInStop', 2],
      [MMSystem.stub, 'waveInReset', 2],
      [MMSystem.stub, 'waveInGetPosition', 8],
      [MMSystem.stub, 'waveInGetID', 6],
      [MMSystem.stub, 'waveInMessage', 12],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 520 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 530 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 540 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 550 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 560 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 570 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 580 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 590 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 600 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'timeGetSystemTime', 6],
      [MMSystem.stub, 'timeSetEvent', 14],
      [MMSystem.stub, 'timeKillEvent'],
      [MMSystem.stub, 'timeGetDevCaps', 6],
      [MMSystem.stub, 'timeBeginPeriod'],
      [MMSystem.stub, 'timeEndPeriod'],
      [MMSystem.stub, 'timeGetTime'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 610 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 620 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 630 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 640 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 650 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 660 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 670 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 680 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 690 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'unknown'],
      // 700 //
      [MMSystem.stub, 'unknown'],
      [MMSystem.stub, 'mciSendCommand', 12],
      [MMSystem.stub, 'mciSendString', 12],
      [MMSystem.stub, 'mciGetDeviceID', 4],
      [MMSystem.stub, 'mciParseCommand'],
      [MMSystem.stub, 'mciLoadCommandResource', 8],
      [MMSystem.stub, 'mciGetErrorString', 10],
      [MMSystem.stub, 'mciSetDriverData', 6],
      [MMSystem.stub, 'mciGetDriverData', 2],
      null,
      [MMSystem.stub, 'MCIDRIVERYIELD', 2],
      null,
      [MMSystem.stub, 'MCIEXECUTE', 4],
      [MMSystem.stub, 'MCIFREECOMMANDRESOURCE', 2],
      [MMSystem.stub, 'MCISETYIELDPROC', 10],
      [MMSystem.stub, 'MCIGETDEVICEIDFROMELEMENTID', 8],
      [MMSystem.stub, 'MCIGETYIELDPROC', 6],
      [MMSystem.stub, 'MCIGETCREATORTASK', 2],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [MMSystem.stub, 'MMTASKCREATE', 12],
      null,
      [MMSystem.stub, 'MMTASKBLOCK', 2],
      null,
      null,
      [MMSystem.stub, 'MMTASKYIELD', 0],
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      [MMSystem.stub, 'MMIOOPEN', 12],
      [MMSystem.stub, 'MMIOCLOSE', 4],
      [MMSystem.stub, 'MMIOREAD', 10],
      [MMSystem.stub, 'MMIOWRITE', 10],
      [MMSystem.stub, 'MMIOSEEK', 8],
      [MMSystem.stub, 'MMIOGETINFO', 8],
      [MMSystem.stub, 'MMIOSETINFO', 8],
      [MMSystem.stub, 'MMIOSETBUFFER', 12],
      [MMSystem.stub, 'MMIOFLUSH', 4],
      [MMSystem.stub, 'MMIOADVANCE', 8],
      [MMSystem.stub, 'MMIOSTRINGTOFOURCC', 6],
      [MMSystem.stub, 'MMIOINSTALLIOPROC', 12],
      [MMSystem.stub, 'MMIOSENDMESSAGE', 12],
      [MMSystem.stub, 'MMIODESCEND', 12],
      [MMSystem.stub, 'MMIOASCEND', 8],
      [MMSystem.stub, 'MMIOCREATECHUNK', 8],
      [MMSystem.stub, 'MMIORENAME', 16],
    ];
  }

  static stub() {
    console.log('Stub called!');
  }
}

/**
 * The **WAVEFORMAT** structure describes the format of waveform data. Only
 * format information common to all waveform data formats is included in this
 * structure. For formats that require additional information, this structure is
 * included as a field in another data structure along with the additional
 * information.
 */
export class WAVEFORMAT extends Struct {
  constructor() {
    super([
      ['wFormatTag', UINT], // format type. WAVE_FORMAT_PCM
      ['nChannels', UINT], // channels
      ['nSamplesPerSec', DWORD], // sample rate (samples per second)
      ['nAvgBytesPerSec', DWORD], // transfer rate (bytes per second)
      ['nBlockAlign', UINT], // block alignment in bytes
    ]);
  }
}

// waveOutOpen Constants
// ---------------------

/**
 * If this flag is specified, the device is be queried to determine if it
 * supports the given format but is not actually opened.
 *
 * @static
 * @constant {number}
 * @memberof MMSystem
 */
MMSystem.WAVE_FORMAT_QUERY = 0x0001;

/**
 * Allows a synchronous (blocking) waveform driver to be opened. If this flag is
 * not set while opening a synchronous driver, the open will fail.
 *
 * @static
 * @constant {number}
 * @memberof MMSystem
 */
MMSystem.WAVE_ALLOWSYNC = 0x0002;

/**
 * If this flag is specified, dwCallback is assumed to be a window handle.
 *
 * @static
 * @constant {number}
 * @memberof MMSystem
 */
MMSystem.CALLBACK_WINDOW = 0x10000;

MMSystem.CALLBACK_TASK = 0x20000;

/**
 * If this flag is specified, dwCallback is assumed to be a callback procedure
 * address.
 *
 * @static
 * @constant {number}
 * @memberof MMSystem
 */
MMSystem.CALLBACK_FUNCTION = 0x30000;

/**
 * Specifies that the wave format being queried or opened is PCM.
 *
 * @static
 * @constant {number}
 * @memberof MMSystem
 */
MMSystem.WAVE_FORMAT_PCM = 0x1;

/**
 * Specifies the device id is the wave mapper device.
 *
 * @static
 * @constant {number}
 * @memberof MMSystem
 */
MMSystem.WAVE_MAPPER = 0xffff; // -1

// General Error Values
// --------------------

MMSystem.MMSYSERR_BASE = 0x0; // 0
MMSystem.WAVERR_BASE = 0x20; // 32
MMSystem.MIDIERR_BASE = 0x40; // 64
MMSystem.TIMERR_BASE = 0x60; // 96
MMSystem.JOYERR_BASE = 0xa0; // 160
MMSystem.MCIERR_BASE = 0x100; // 256

MMSystem.MMSYSERR_NOERROR = 0x0;
MMSystem.MMSYSERR_ERROR = MMSystem.MMSYSERR_BASE + 1;
MMSystem.MMSYSERR_BADDEVICEID = MMSystem.MMSYSERR_BASE + 2;
MMSystem.MMSYSERR_NOTENABLED = MMSystem.MMSYSERR_BASE + 3;
MMSystem.MMSYSERR_ALLOCATED = MMSystem.MMSYSERR_BASE + 4;
MMSystem.MMSYSERR_INVALHANDLE = MMSystem.MMSYSERR_BASE + 5;
MMSystem.MMSYSERR_NODRIVER = MMSystem.MMSYSERR_BASE + 6;
MMSystem.MMSYSERR_NOMEM = MMSystem.MMSYSERR_BASE + 7;
MMSystem.MMSYSERR_NOTSUPPORTED = MMSystem.MMSYSERR_BASE + 8;
MMSystem.MMSYSERR_BADERRNUM = MMSystem.MMSYSERR_BASE + 9;
MMSystem.MMSYSERR_INVALFLAG = MMSystem.MMSYSERR_BASE + 10;
MMSystem.MMSYSERR_INVALPARAM = MMSystem.MMSYSERR_BASE + 11;
MMSystem.MMSYSERR_LASTERROR = MMSystem.MMSYSERR_BASE + 11;
