"use strict";

import { NULL } from '../consts.js';

/**
 * The **SetTimer** function installs a system timer. A time-out value is
 * specified, and every time a time-out occurs, the system posts a `WM_TIMER`
 * message to the installing application's message queue or passes the message
 * to an application-defined TimerProc callback function.
 *
 * Timers are a limited global resource; therefore, it is important that an
 * application check the value returned by the **SetTimer** function to verify
 * that a timer is available.
 *
 * The tmprc parameter must specify a procedure-instance address of the callback
 * function, and the callback function must be exported in the application's
 * module-definition file. A procedure-instance address can be created by using
 * the {@link Kernel.MakeProcInstance MakeProcInstance} function. The callback
 * function must use the Pascal calling convention and must be declared as FAR.
 *
 * @static
 * @function SetTimer
 * @memberof User
 *
 * @param {Types.HWND} hwnd - Identifies the window to be associated with the
 *                            timer. If the `tmprc` parameter is `NULL`, the
 *                            window procedure associated with this window
 *                            receives the `WM_TIMER` messages generated by the
 *                            timer. If this parameter is `NULL`, no window is
 *                            associated with the timer. 
 * @param {Types.UINT} idTimer - Specifies a nonzero timer identifier. If the
 *                               `hwnd` parameter is `NULL`, this parameter is
 *                               ignored. 
 * @param {Types.UINT} uTimeout - Specifies the time-out value, in milliseconds.
 * @param {Types.TIMERPROC} tmprc - Specifies the procedure-instance address of
 *                                  the callback function that processes the
 *                                  `WM_TIMER` messages. If this parameter is
 *                                  `NULL`, the `WM_TIMER` messages are placed
 *                                  in the application's message queue and the
 *                                  `hwnd` member of the MSG structure contains
 *                                  the window handle specified in `hwnd`. For
 *                                  more information, see the description of the
 *                                  `TimerProc` callback function. 
 *
 * @return {Types.UINT} The return value is the identifier of the new timer if
 *                      `hwnd` is `NULL` and the function is successful. An
 *                      application passes this value to the
 *                      {@link User.KillTimer KillTimer} function to kill the
 *                      timer. The return value is nonzero if `hwnd` is a valid
 *                      window handle and the function is successful. Otherwise,
 *                      the return value is zero. 
 */
export function SetTimer(hwnd, idTimer, uTimeout, tmprc) {
    // TODO: does it complain if hwnd is set and idTimer is 0?

    let dialog = null;
    if (hwnd != NULL) {
        dialog = this.handles.resolve(hwnd);
    }

    // Kinda reduce the frequency to match the frequency of the era
    uTimeout = Math.max(uTimeout, 55);

    let pending = false;
    window.setInterval( () => {
        if (tmprc == NULL) {
            // Send a WM_TIMER message
            if (!pending) {
                let task = this.handles.resolve(dialog.data.hInstance);
                pending = true;
                this.windows.createMessage(dialog.data.hInstance, task, dialog.data.hWnd, 'timer', {id: idTimer}, () => {
                    pending = false;
                }); 
            }
        }
        else {
            // We call the tmprc (timer-proc) function
            console.log("oh my");
        }
    }, uTimeout);

    return idTimer;
}
