//! Windows 3.1 itself, in Rust: a program loaded from its file and linked
//! to the modules it calls.

pub mod accelerators;
pub mod accessible_tree;
pub mod atoms;
pub mod audio;
pub mod button;
pub mod call;
pub mod call_costs;
pub mod call_marks;
pub mod caret;
pub mod classes;
pub mod clipboard;
pub mod combobox;
pub mod comm;
pub mod control_host;
pub mod control_paint;
pub mod control_pixels;
pub mod controls;
pub mod create;
pub mod cursor_pos;
pub mod def_window;
pub mod desktop;
pub mod desktop_paint;
pub mod destroy;
pub mod dialog_template;
pub mod dialogs;
pub mod display;
pub mod dlgdir;
mod dos;
pub mod draw_text;
pub mod drivers;
pub mod edit;
pub mod edit_buffer;
pub mod edit_paint;
pub mod engine;
pub mod enumerate;
pub mod fault;
mod fault_vector;
mod files_kernel;
pub mod fm;
pub mod fonts;
pub mod frame;
pub mod gdi;
pub mod get_dc;
pub mod handles;
pub mod hooks;
pub mod host;
pub mod icons;
mod instruction_length;
pub mod interrupts;
mod kept;
pub mod kernel;
pub mod kernel_calls;
pub mod key_input;
pub mod keyboard;
pub mod linker;
pub mod listbox;
pub mod loader;
pub mod mdi;
pub mod mdi_scroll;
mod memory;
pub mod menu_api;
pub mod menu_bar;
pub mod menu_default;
pub mod menu_loop;
pub mod menu_popup;
pub mod menus;
pub mod messages;
pub mod mledit;
pub mod mmsystem;
pub mod modules;
mod modules_kernel;
pub mod paint;
pub mod painter;
mod pointers;
mod ports;
pub mod position;
pub mod present;
pub mod printer;
pub mod profile;
mod profiles_kernel;
pub mod queue;
pub mod raster_input;
pub mod resources;
mod run;
pub mod scheduler;
pub mod scroll_bars;
pub mod shell;
pub mod sound;
pub mod surface;
pub mod survey;
pub mod sys_error_box;
pub mod system;
pub mod task;
pub mod tasks;
pub mod timer;
pub mod toolhelp;
pub mod track_loop;
pub mod user;
pub mod user_calls;
pub mod user_comm;
pub mod user_misc;
pub mod wbmapper;
pub mod wbsound;
pub mod win87em;
pub mod window_misc;
pub mod window_queries;
pub mod window_state;
pub mod windows;
pub mod wing;

pub use call::{Answer, Call, Stop};
pub use engine::{Engine, EngineRun, Pace, Register, Step};
pub use loader::Module;
pub use modules::{Export, Kept};
pub use system::System;
