//! Windows 3.1 itself, in Rust: a program loaded from its file and linked
//! to the modules it calls.

pub mod accelerators;
pub mod atoms;
pub mod call;
pub mod classes;
pub mod create;
pub mod cursor_pos;
pub mod def_window;
pub mod desktop;
pub mod destroy;
pub mod display;
mod dos;
pub mod engine;
pub mod enumerate;
mod files_kernel;
pub mod fonts;
pub mod gdi;
pub mod get_dc;
pub mod handles;
pub mod hooks;
pub mod icons;
mod kept;
pub mod kernel;
pub mod keyboard;
pub mod linker;
pub mod loader;
mod memory;
pub mod menu_api;
pub mod menu_bar;
pub mod menus;
pub mod messages;
pub mod modules;
mod modules_kernel;
pub mod paint;
mod pointers;
pub mod position;
pub mod profile;
mod profiles_kernel;
pub mod queue;
pub mod raster_input;
pub mod resources;
mod run;
pub mod surface;
pub mod system;
pub mod task;
pub mod toolhelp;
pub mod user;
pub mod user_misc;
pub mod win87em;
pub mod window_misc;
pub mod window_queries;
pub mod window_state;
pub mod windows;

pub use call::{Answer, Call, Stop};
pub use engine::{Engine, Register};
pub use loader::Module;
pub use modules::{Export, Kept};
pub use system::System;
